-- function ToggleNetrw()
-- 	if vim.api.nvim_get_option_value("filetype", {}) == "netrw" then
-- 		vim.api.nvim_exec2("close", {})
-- 	else
-- 		vim.api.nvim_exec2(":Vexplore", {})
-- 	end
-- end
--
-- vim.keymap.set("n", "<C-e>", ToggleNetrw)
